name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: Linux

          - os: macos-latest
            target: Macos

          - os: windows-latest
            target: Windows

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Pack-source
        run: mkdir ${{github.workspace}}/args_${{matrix.os}}_${{env.BUILD_TYPE}}_source &
             cd ${{github.workspace}}/args_${{matrix.os}}_${{env.BUILD_TYPE}}_source &
             cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

      - name: Pack-source-artifact
        uses: actions/upload-artifact@v2
        with:
          name: args_${{matrix.os}}_${{env.BUILD_TYPE}}_source
          path: ${{github.workspace}}/args_${{matrix.os}}_${{env.BUILD_TYPE}}

      - name: Pack-build

        run: mkdir ${{github.workspace}}/args_${{matrix.os}}_${{env.BUILD_TYPE}} &
             cd ${{github.workspace}}/args_${{matrix.os}}_${{env.BUILD_TYPE}} &
             cpack --config ${{github.workspace}}/build/CPackConfig.cmake

      - name: Pack-build-artifact
        uses: actions/upload-artifact@v2
        with:
          name: args_${{matrix.os}}_${{env.BUILD_TYPE}}
          path: ${{github.workspace}}/args_${{matrix.os}}_${{env.BUILD_TYPE}}